server:
  port: 8080

spring:
  datasource:
    # Default for local dev when MySQL container exposes 3307 on host
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/ecinema?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8}
    username: ${SPRING_DATASOURCE_USERNAME:cinemae}
    password: ${SPRING_DATASOURCE_PASSWORD:devsecret}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate     # validate | none | update | create-drop (use validate or none in dev)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  flyway:
    enabled: false           # enable if you use Flyway migrations
